#!/bin/bash
#######################################################################################################################
#
#  This shell script will run unit tests avilable in SQL Developer.
#  It wll also p[rovide detailed and summary reports of those unit tests, and it will send
#  emails to interested parties.
# 
# This script will take input as below.
#
# Position       parameter_name                         Description
#
#  1              suit_name	                 Name of the test suit as per the SQL developer.
#
#  2              db_name                        Name of the database connection as per SQL Developer
#
#  3              db_user                        Database user id to be used to generate the report.
#
#  4              db_passwd                      Database password to be used to generate the report.  
#
#  5              db_conn_details                Database connection details or db_name as per the tnsname.ora file
#
#  6              cmd_dir                        Full path of bin dir as per SQL Developer.
#
#  7              repo_name                      Name of the test repository as per SQL Developer.
#
#  8              temp_file_dir                  This is the path of the directory where some temp files will be created
#                                                and deleted after processing.
#  
#  9              arc_dir                        full path of the archieve directory.
#
#  10             mail_recipient                 List of mail ids of interested parties, this will be a comma separated
#                                                list.
######################################################################################################################### 
 
## Assigning value to variables
op_file=$9/$1`date +%Y%m%d%k%M%S`.csv
suit_name=$1
db_name=$2
db_user=$3
db_passwd=$4
db_conn_details=$5
cmd_dir=$6
repository=$7
temp_dir=$8
arc_dir=$9
mail_rep=${10}
ip=${11}

#Getting the current directory
cur_dir=`pwd`

# Getting the unique value generated by the unit test run of the suite.
cd $cmd_dir
uniq_key=`./sdcli unittest -run -suite -name $suit_name -repo $repository -db $db_name -log 3 |head -5 | tail -1 `
uniq_key=\'$uniq_key\'

# Generating the detailed report 
suit_name=\'$suit_name\'
sqlplus -s $db_user/$db_user$ip/$db_conn_details <<DB_ST>$op_file
SET lin 4000
SET verify OFF
SET term OFF
SET timing OFF
SET echo OFF
SET feedback OFF
set colsep ,
SET pagesize 0
SET trim OFF
SELECT 'SUITE'
  ||','
  || 'TEST_SCENARIO'
  ||','
  || 'TEST_CASE'
  ||','
  || 'STATUS'
  ||','
  ||'MESSAGE' 
from dual;
SELECT sr.name Suite,
  tr.name Test_scenario,
  tir.name test_case,
  DECODE(tir.status,'UT_SUCCESS','Success','UT_ERROR','Failed',tir.status) status,
  --tir.message
  REPLACE(REPLACE(NVL(tir.message,' '),CHR(44),'-'),CHR(10),' ' )MESSAGE
FROM ut_suite_results sr,
  ut_suite_item_results str,
  ut_test_results tr,
  ut_test_impl_results tir
WHERE str.utsr_id = sr.utsr_id
AND str.utr_id    = tr.utr_id
AND TIR.UTR_ID    = TR.UTR_ID
AND sr.name       = $suit_name
AND sr.utsr_id    = $uniq_key
ORDER BY TR.RUN_DATE;
exit;
DB_ST

# Generating the summary report 

echo " Detailed report is attached here with this mail. " >$temp_dir/sumrep.txt
echo " Below is the summary report for the unit test run of the suite $suit_name for database :$ip  " >>$temp_dir/sumrep.txt
sqlplus -s $db_user/$db_user$ip/$db_conn_details<<DB_ST>>$temp_dir/sumrep.txt
SET serveroutput ON;
SET lin 4000
SET verify OFF
SET term OFF
SET timing OFF
SET echo OFF
SET feedback OFF
SET pagesize 0
SELECT COUNT(*),
  'Total' AS status
FROM ut_suite_results sr,
  ut_suite_item_results str,
  ut_test_results tr,
  ut_test_impl_results tir
WHERE str.utsr_id = sr.utsr_id
AND str.utr_id    = tr.utr_id
AND TIR.UTR_ID    = TR.UTR_ID
AND SR.name       =$suit_name
AND sr.utsr_id    =$uniq_key
UNION ALL
SELECT COUNT(*),
  DECODE(TIR.STATUS,'UT_SUCCESS','Success','UT_ERROR','Failed',TIR.STATUS) AS status
FROM ut_suite_results sr,
  ut_suite_item_results str,
  ut_test_results tr,
  ut_test_impl_results tir
WHERE str.utsr_id = sr.utsr_id
AND str.utr_id    = tr.utr_id
AND TIR.UTR_ID    = TR.UTR_ID
AND SR.name       =$suit_name
AND SR.UTSR_ID    =$uniq_key
GROUP BY TIR.STATUS
ORDER BY status DESC;
exit;
DB_ST

cd $cur_dir
echo $mail_rep
#mail_rep=\'$mail_rep\'
#Sending mail with reports

mailx -s "Unit Testing on $db_name " -a $op_file $mail_rep < $temp_dir/sumrep.txt
rm $temp_dir/sumrep.txt
