#!/bin/bash
#######################################################################################################################
#
#  This shell script will run unit tests avilable in SQL Developer.
#  It wll also p[rovide detailed and summary reports of those unit tests, and it will send
#  emails to interested parties.
# 
# This script will take input as below.
#
# Position       parameter_name                         Description
#
#  1              suit_name	                 Name of the test suit as per the SQL developer.
#
#  2              repository                      Name of the test repository as per SQL Developer.
#
#  3              cmd_dir                        Full path of bin dir as per SQL Developer.
#
#  4              impo				path of file to import tests from
#
######################################################################################################################### 
 ## Assigning value to variables

suit_name=$1
repository=$2
cmd_dir=$3
impo=$4
#Getting the current directory
cur_dir=`pwd`

cd $cmd_dir
./sdcli unittest -imp -repo $repository -file $impo

cd $cur_dir
